---
os: linux
dist: bionic

language: python
python: 3.9
cache: pip

before_script: pip install -U sphinx
script: make clean html

deploy:
  - provider: pages
    verbose: true
    github_token: $GITHUB_TOKEN
    edge: true
    local_dir: ./_build/html/
    keep_history: true
    on:
      branch: main
